### ISSUE TITLE
MadgwickAHRS library not searchable in library manager

### ISSUE THREAD

**Issue by X-Y** [arduino/tutorials#3]
Hi in the tutorial text it's mentioned that the Madgwick library can be found in library manager, but I couldn't get it through the search function. Wondering if it's a good place to post this issue? I'm using Arduino 1.6.7

**Comment by per1234** [comment]
The tutorial in question:
https://www.arduino.cc/en/Tutorial/Genuino101CurieIMUOrientationVisualiser
>Install the Madgwick library from library manager. To do this, open the Arduino Software (IDE), go to "Sketch -> Include Library -> Manage Libraries". There you can search 'Madgwick' and install the library directly from there.

I find the library in Library Manager with a search for 'Madgwick', so I believe this can be closed.
